# Generated by Django 3.0.4 on 2020-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название заголовка')),
                ('information', models.TextField(verbose_name='Информация')),
                ('last_upd', models.DateTimeField(verbose_name='Последняя дата обновлении')),
            ],
        ),
    ]
